### ISSUE TITLE
Plugin Error in RVIZ

### ISSUE THREAD

**Issue by hichamhendy** [naturerobots/mesh_tools#16]
I am getting the following error by adding the plugin in RVIZ

`[ERROR] [1659346788.464576399]: PluginlibFactory: The plugin for class 'rviz_map_plugin/Mesh' failed to load.  Error: Failed to load library /home/rnd/catkin_ws/devel/lib//librviz_map_plugin.so. Make sure that you are calling the PLUGINLIB_EXPORT_CLASS macro in the library code, and that names are consistent between this macro and your XML. Error string: Could not load library (Poco exception = /home/rnd/catkin_ws/devel/lib/libhdf5_map_io.so: undefined symbol: _ZN3MPI3Win4FreeEv)`

Anyone has an idea??

**Comment by JinXJinLeX** [comment]
I have same problem , also want so ask how to solve?

**Comment by amock** [comment]
I could not reproduce this error on the current version of humble and noetic. If this error still remains, feel free to reopen this issue and to provide an instruction on how to reproduce the error.
