### ISSUE TITLE
How can I generate Mesh map from point cloud

### ISSUE THREAD

**Issue by liuxiao916** [naturerobots/mesh_tools#20]
Hi, 

Thank you for your nice work.

Can you give me some example that how to generate Mesh Map from point cloud? It will be helpful.  : )

**Comment by JACKLiuDay** [comment]
I have the same problem.

**Comment by aock** [comment]
Hello Xiao Liu,

thanks for your interest in our work. We often use high-resolution point clouds from terrestrial laser scanners. After we have registered all the clouds into a large unordered point cloud, we use lvr2, Open3D or meshlab to finally reconstruct the meshes, in an offline fashion. In recent years, more and more software packages for online mesh generation have also emerged. To give you a good starting point for your research, here is a list of links:

- https://github.com/uos/lvr2
	- for example the lvr2_reconstruct executable
- https://www.open3d.org/
	- Some scripts: https://github.com/naturerobots/open3d_scripts
- https://www.meshlab.net/
- https://www.microsoft.com/en-us/research/wp-content/uploads/2016/02/ismar2011.pdf
- https://github.com/PRBonn/puma
- https://github.com/lab-sun/SLAMesh
- https://github.com/MIT-SPARK/Kimera-VIO
- https://github.com/juliangaal/warpsense
- https://github.com/nvidia-isaac/nvblox
- https://github.com/ethz-asl/voxblox

It is not planned to integrate the reconstruction of surfaces from point clouds into mesh_tools.

Greetings and happy meshing
Alex
