### ISSUE TITLE
fatal error: mesh_msgs/TriangleIndices.h: No such file or directory

### ISSUE THREAD

**Issue by USTCerzmj** [naturerobots/mesh_tools#29]
Hello, I highly appreciate your work. While replicating your work, I encountered the following issues:

Fatal error: mesh_msgs/GetUUID.h: No such file or directory
Fatal error: mesh_msgs/TriangleIndices.h: No such file or directory
Could you provide the corresponding GetUUID.srv and TriangleIndices.msg files?

**Comment by aock** [comment]
I will close this issue due to inactivity

**Comment by vanstrong12138** [comment]
> Hi USTCerzmj,
> 
> thanks for your interest. Could you provide some more details about your setup?
> 
> * Are you installing from source or do you use the precompiled binaries (apt install ros-*-mesh-tools)?
> * Which operating system do you use?
> * Which ROS version do you use?
> * If you compile from source:
>   
>   * Which branch of mesh_tools do you use?
> 
> Furthermore, it would be very helpful if you post all of your error message.
> 
> Greetings Alex

same problem
ubuntu20.04    ROS noetic    noetic branch

**Comment by vanstrong12138** [comment]
> Hello, I highly appreciate your work. While replicating your work, I encountered the following issues:
> 
> Fatal error: mesh_msgs/GetUUID.h: No such file or directory Fatal error: mesh_msgs/TriangleIndices.h: No such file or directory Could you provide the corresponding GetUUID.srv and TriangleIndices.msg files?

兄弟怎么解决的
