### ISSUE TITLE
document/add tool for converting meshes to hdf5 for mesh navigation

### ISSUE THREAD

**Issue by Cakem1x** [naturerobots/mesh_tools#37]
Currently, mesh navigation needs a HDF5 mesh to function.
There is a CLI tool in `lvr2` with which one can convert different mesh formats to a `.h5` mesh. The conversion only works for simple input formats, e.g. `.ply`.

The goal of this issue is to have an easy to use converter in the `mesh_tools` pkg, accessible via ros2 cli tools. It is sufficient if it only supports `.ply` files, but more would be nice. Though only if it works reliably.

When converting, check 
* the existing lvr2 script
* where the mesh_map in [mesh_navigation](https://github.com/naturerobots/mesh_navigation) loads maps and precomputes values

and consider
* normals (calculations seem off; use weighted face normals instead)
* colors

**Comment by amock** [comment]
I think this issue is solved with the new docs of the [mesh_navigation_tutorials](https://github.com/naturerobots/mesh_navigation_tutorials/wiki).

So I guess we can close this now.
